// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWMJXna2L564pfnofpzsj53329f_wefQ',
    appId: '1:348255442043:web:23cf2cd1ac569d8cc87ede',
    messagingSenderId: '348255442043',
    projectId: 'groceryapp-1a911',
    authDomain: 'groceryapp-1a911.firebaseapp.com',
    storageBucket: 'groceryapp-1a911.appspot.com',
    measurementId: 'G-E4QVRH8W1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCdQyO6e_ZwAfXjsh2f82VlHNSSQG8xI',
    appId: '1:348255442043:android:819fb6584f6dae33c87ede',
    messagingSenderId: '348255442043',
    projectId: 'groceryapp-1a911',
    storageBucket: 'groceryapp-1a911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArm1kG_2Z3zH7WpEoN90plphQDV2CrwVw',
    appId: '1:348255442043:ios:15227be59f8d48ffc87ede',
    messagingSenderId: '348255442043',
    projectId: 'groceryapp-1a911',
    storageBucket: 'groceryapp-1a911.appspot.com',
    iosClientId: '348255442043-ge78ubru0aumecdmr81ianf83us1727q.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArm1kG_2Z3zH7WpEoN90plphQDV2CrwVw',
    appId: '1:348255442043:ios:5b1711fe5f0a0cdbc87ede',
    messagingSenderId: '348255442043',
    projectId: 'groceryapp-1a911',
    storageBucket: 'groceryapp-1a911.appspot.com',
    iosClientId: '348255442043-qh0pdfkfnfs4gh6uq8qdslslga829s75.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
